steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spoteye-monitor:$BUILD_ID', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spoteye-monitor:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'spoteye-monitor'
    - '--image=gcr.io/$PROJECT_ID/spoteye-monitor:$BUILD_ID'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--timeout=900'
    - '--max-instances=1'
    - '--min-instances=0'
    - '--set-env-vars=SMTP_USER=tanga6998@gmail.com,SMTP_PASSWORD=idylhzpoddvbwqhu,RECIPIENT_EMAIL=tr1173309602@gmail.com'

images:
  - 'gcr.io/$PROJECT_ID/spoteye-monitor:$BUILD_ID' 